# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fr.document-core
canonical: https://interop.esante.gouv.fr/ig/document-core # the last part of canonical and id must be the same
name: FRDocumentCore # Should be an acronym
title: FR Document Core (Modèle métier)
description: Volet modèle métier du guide d'implémentation Document Core.
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: draft
version: 0.1.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
license: CC0-1.0
releaseLabel: ci-build # le release label doit être conforme au cycle de vie de la doctrine du ci-sis. Cf. https://interop.esante.gouv.fr/ig/documentation/mod_bonnes_pratiques.html#release-dun-ig-fhir colonne "label de publication"

jurisdiction: urn:iso:std:iso:3166#FR "France (la)"

parameters: #Parameters list - https://build.fhir.org/ig/FHIR/fhir-tools-ig/CodeSystem-ig-parameters.html
    shownav: 'true'
    path-expansion-params: '../../expansion-params.json' # for using French SNOMED CT Extension
    pin-canonicals: pin-all
    apply-contact: true
    logging:
      - tx #tx: Messages describing the use of the terminology server (for debugging)
      - html #html: Log when validating an html page (troubleshooting only - leave off)
      - generate #generate: Log when producing an individual resource (troubleshooting only - leave off)
      - init #init: Messages describing the start up process (for debugging)
      - progress #progress: Overall progress messages
    i18n-default-lang: fr # Default language
    apply-jurisdiction: true
    i18n-lang:
      - en
    translation-sources:
      - input/translations/en

dependencies:
  ans.fr.terminologies: latest
  ans.fhir.fr.document-core: current
  ans.cda.fr.document-core: current


pages:
    index.md:
        title: Accueil
    structureGenerale.md:
        title: Structure générale document
        introduction.md:
            title: Introduction
        exigencesSpecifiques.md:
            title: Exigences spécifiques
        mappingCDA-FHIR-struc-gen.md:
            title: Mapping CDA / FHIR
    enteteDocument.md:
        title: Entête document
        mappingCDA-FHIR-entete.md:
            title: Mapping Métier/CDA/FHIR
    corpsDocument.md:
        title: Corps d'un document
        mappingCDA-FHIR-corps.md:
            title: Mapping Métier/CDA/FHIR
    autres_ressources.md:
        title: Autres Ressources
        securite.md:
            title: Sécurité
        downloads.md:
            title: Téléchargements et usages
    translationinfo.md:
        title: Informations sur la traduction

menu:
    Accueil: index.html
    Structure générale document:
        Introduction: introduction.html
        Exigences spécifiques: exigencesSpecifiques.html
        Mapping CDA / FHIR: mappingCDA-FHIR-struc-gen.html
    Entête document:
        Modèle logique métier: StructureDefinition-fr-lm-header-document.html
        Mapping Métier/CDA/FHIR: mappingCDA-FHIR-entete.html
    Corps d'un document:
        Modèle logique métier: StructureDefinition-fr-lm-corps-document.html
        Mapping Métier/CDA/FHIR: mappingCDA-FHIR-corps.html
    Ressources de conformité: artifacts.html
    Autres ressources:
        "IG FHIR": new-tab https://interop.esante.gouv.fr/ig/fhir/document-core/index.html
        "IG CDA": new-tab https://interop.esante.gouv.fr/ig/cda/document-core/index.html
        "Espace de publication du CI-SIS": new-tab https://esante.gouv.fr/offres-services/ci-sis/espace-publication
        "Serveur Multi-terminologies": new-tab https://smt.esante.gouv.fr/
        "Serveur Multi-terminologies / FHIR": new-tab https://smt.esante.gouv.fr/fhir
        "IG terminologies et jeux de valeurs du CI-SIS": new-tab https://ansforge.github.io/IG-terminologie-de-sante/ig/main/index.html
        "Espace de tests du CI-SIS": new-tab https://interop.esante.gouv.fr/
        Sécurité: securite.html
        "Standard CDA": new-tab https://hl7.org/cda/stds/online-navigation/index.html
        "Standard FHIR": new-tab https://hl7.org/fhir/R4/index.html
        "Documentation des guides d'implémentation de l'ANS": new-tab https://interop.esante.gouv.fr/ig/documentation/index.html
        Téléchargements et usage: downloads.html

groups:
  header-models:
    name: Modèles logiques métier de l'entête d'un document
    resources:
      - FRLMHeaderDocument	
      - FRLMPatient
      - FRLMHealthProfessional
      - FRLMOrganisation
      - FRLMInformant
      - FRLMIntendedRecipient
      - FRLMLegalAuthentication
      - FRLMAttester
      - FRLMDataEnterer
      - FRLMParticipant
      - FRLMOrder
      - FRLMConsent
      - FRLMLocation
      - FRLMRelatedPerson
      - FRLMHumanName

  section-models: 
    name: Modèles logiques métier des sections d'un document
    resources: []

  common-models: 
    name: Modèles logiques métier des composants communs
    description: Modèles de données métier représentant les concepts communs, modélisés indépendamment de la syntaxe et de façon plus accessible pour le métier que les éléments techniques CDA et FHIR.
    resources:
      - StructureDefinition/fr-lm-entry
      - StructureDefinition/fr-lm-procedure
      - StructureDefinition/fr-lm-family-member-history
      - StructureDefinition/fr-lm-service-request
      - StructureDefinition/fr-lm-care-plan
      - StructureDefinition/fr-lm-condition
      - StructureDefinition/fr-lm-encounter
      - StructureDefinition/fr-lm-observation
      - StructureDefinition/fr-lm-allergy-intolerance	
      - StructureDefinition/fr-lm-advance-directive
      - StructureDefinition/fr-lm-device-use
      - StructureDefinition/fr-lm-attachment
      - StructureDefinition/fr-lm-adverse-drug-reaction
      - StructureDefinition/fr-lm-observation-assessment
      - StructureDefinition/fr-lm-observation-social-history
      - StructureDefinition/fr-lm-observation-media
      - StructureDefinition/fr-lm-pregnancy-observation
      - StructureDefinition/fr-lm-pregnancy-status
      - StructureDefinition/fr-lm-pregnancy-history
      - StructureDefinition/fr-lm-medication
      - StructureDefinition/fr-lm-dose-number
      - StructureDefinition/fr-lm-resultats-examens-biologie-medicale
      - StructureDefinition/fr-lm-observation-vital-sign
      - StructureDefinition/fr-lm-medication-administration
      - StructureDefinition/fr-lm-dicom-medication-administration
      - StructureDefinition/fr-lm-immunisation
      - StructureDefinition/fr-lm-medication-dispense
      - StructureDefinition/fr-lm-specimen
      - StructureDefinition/fr-lm-batterie-examens-biologie-medicale
      - StructureDefinition/fr-lm-isolat-microbiologique
      - StructureDefinition/fr-lm-resultat-examens-biologie-element-clinique-pertinent
      - StructureDefinition/fr-lm-imaging-study
      - StructureDefinition/fr-lm-series
      - StructureDefinition/fr-lm-sop-instance
      - StructureDefinition/fr-lm-prescription-item
      - StructureDefinition/fr-lm-quantity-exposure
      - StructureDefinition/fr-lm-transfusion-de-produits-sanguins
      - StructureDefinition/fr-lm-multidrug-resistant-microorganism-identification
      - StructureDefinition/fr-lm-transfusion-accidents
      - StructureDefinition/fr-lm-patient-transfer
      - StructureDefinition/fr-lm-laboratoire-executant
      - StructureDefinition/fr-lm-device
      - StructureDefinition/fr-lm-dosageInstructions
      - StructureDefinition/fr-lm-prescription-entree
      - StructureDefinition/fr-lm-laboratory-observation
      - StructureDefinition/fr-lm-body-structure
      - StructureDefinition/fr-lm-travel-history
  
  header-mappings:
    name: Concept Maps de l'entête du document
    resources:
      - mappingmodelemetierCDAFHIR
      - mappingPatientCDAFHIR
      - mappingAuteurCDAFHIR
      - mappingOperateurSaisieCDAFHIR	
      - mappingInformateurCDAFHIR
      - mappingStructureConservationCDAFHIR
      - mappingDestinatairePrevuCDAFHIR
      - mappingResponsableCDAFHIR
      - mappingValidateurCDAFHIR
      - mappingParticipantCDAFHIR
      - mappingPrescriptionCDAFHIR
      - mappingEvenementCDAFHIR
      - mappingDocumentDeReferenceCDAFHIR
      - mappingConsentementCDAFHIR
      - mappingPriseEnchargeCDAFHIR
      - mappingPersonneStructureAssignedEntityFHIR
      - mappingPersonneStructureRelatedEntityFHIR
      - mappingPersonneStructureAuteurFHIR
      - mappingSystemeFHIR

  section-mappings:
    name: Concept Maps des sections d'un document
    resources:
      - FRSectionImagingResultsLMCDAFHIR
      - FRSectionImagingClinicalInformationLMCDAFHIR
      - FRSectionImagingServiceRequestLMCDAFHIR
      - FRSectionImagingRadiationExposureLMCDAFHIR
      - FRSectionImagingActLMCDAFHIR
      - FRSectionImagingAddendumLMCDAFHIR
      - FRSectionSocialHistoryLMCDAFHIR
      - FRSectionFunctionalStatusLMCDAFHIR
      - FRSectionPhysicalFunctionsLMCDAFHIR
      - FRSectionAllergyIntoleranceLMCDAFHIR
      - FRSectionFamilyHistoryLMCDAFHIR
      - FRSectionBarCodesLMCDAFHIR
      - FRSectionNoteLMCDAFHIR
      - FRSectionImagingComparisonLMCDAFHIR
      - FRSectionImagingComplicationsLMCDAFHIR
      - FRSectionImagingConclusionLMCDAFHIR
      - FRSectionMedicalHistoryLMCDAFHIR
      - FRSectionLaboratoryChapterLMCDAFHIR
      - FRSectionLaboratorySubChapterLMCDAFHIR
      - FRSectionAdvanceDirectiveLMCDAFHIR
      - FRSectionMedicalDeviceLMCDAFHIR
      - FRSectionPDFDocumentCopyLMCDAFHIR
      - FRSectionAddedDocumentsLMCDAFHIR
      - FRSectionPatientEducationLMCDAFHIR
      - FRSectionAdverseEventLMCDAFHIR
      - FRSectionExposureRadiationLMCDAFHIR
      - FRSectionUncodedOccupationalRiskFactorsLMCDAFHIR
      - FRSectionHistoryActsLMCDAFHIR
      - FRSectionPregnancyHistoryLMCDAFHIR
      - FRSectionImagingObjectCatalogLMCDAFHIR
      - FRSectionCarePlanLMCDAFHIR
      - FRSectionUncodedPointsOfVigilanceLMCDAFHIR
      - FRSectionPrescriptionOfMedicalDevicesLMCDAFHIR
      - FRSectionMedicationRequestLMCDAFHIR
      - FRSectionActiveProblemsLMCDAFHIR
      - FRSectionReasonForRecommendationLMCDAFHIR
      - FRSectionUncodedReasonForRecommendationLMCDAFHIR
      - FRSectionResultsLMCDAFHIR
      - FRSectionExaminationResultsLMCDAFHIR
      - FRSectionUncodedExaminationResultsLMCDAFHIR
      - FRSectionLaboratorySecondIntentionResultsLMCDAFHIR
      - FRSectionVitalSignsLMCDAFHIR
      - FRSectionDocumentStatusLMCDAFHIR
      - FRSectionMedicationsLMCDAFHIR
      - FRSectionMedicationAdministrationLMCDAFHIR
      - FRSectionHospitalDischargeMedicationsLMCDAFHIR
      - FRSectionImmunizationsLMCDAFHIR
      - FRSectionMedicationDispenseLMCDAFHIR

  common-mappings:
    name: Concept Maps des composants communs d'un Document
    resources:
      - FRProcedureLMCDAFHIR
      - FRAdvanceDirectiveLMCDAFHIR
      - FRAdverseDrugReactionLMCDAFHIR
      - FRAllergyIntoleranceLMCDAFHIR
      - FRCarePlanLMCDAFHIR
      - FRConditionLMCDAFHIR
      - FRDeviceLMCDAFHIR
      - FRDeviceUseLMCDAFHIR
      - FRAttachmentLMCDAFHIR
      - FREncounterLMCDAFHIR
      - FRFamilyMemberHistoryLMCDAFHIR
      - FRImagingStudyLMCDAFHIR
      - FRImmunisationLMCDAFHIR
      - FRMediaLMCDAFHIR
      - FRMedicationAdministrationLMCDAFHIR
      - FRMedicationDispenseLMCDAFHIR
      - FRMedicationLMCDAFHIR
      - FRMedicationRequestLMCDAFHIR
      - FRMedicationStatementLMCDAFHIR
      - FRLaboratoryIsolateResultsLMCDAFHIR
      - FRLaboratoryBatteryResultsLMCDAFHIR
      - FRLaboratoryResultsLMCDAFHIR
      - FRLaboratoryResultClinicalElementLMCDAFHIR
      - FRObservationMicroorganismDetectionLMCDAFHIR
      - FRObservationMultiresistantMicroorganismsIdentificationLMCDAFHIR
      - FRObservationPregnancyLMCDAFHIR
      - FRImagingQuantityExposureLMCDAFHIR
      - FRObservationResultLMCDAFHIR
      - FRObservationSocialHistoryLMCDAFHIR
      - FRObservationAssessmentLMCDAFHIR
      - FRObservationVitalSignsLMCDAFHIR
      - FRPregnancyHistoryLMCDAFHIR
      - FRServiceRequestLMCDAFHIR
      - FRSpecimenLMCDAFHIR
      - FRImagingMedicationAministrationLMCDAFHIR
      - FRParticipantCorpsLMCDAFHIR
      - FRObservationLMCDAFHIR