# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fr.document-core
canonical: https://interop.esante.gouv.fr/ig/document-core # the last part of canonical and id must be the same
name: FRDocumentCore # Should be an acronym
title: FR Document Core (Modèle métier)
description: Volet modèle métier du guide d'implémentation Document Core.
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: draft
version: 0.1.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
license: CC0-1.0
releaseLabel: ci-build # le release label doit être conforme au cycle de vie de la doctrine du ci-sis. Cf. https://interop.esante.gouv.fr/ig/documentation/mod_bonnes_pratiques.html#release-dun-ig-fhir colonne "label de publication"

jurisdiction: urn:iso:std:iso:3166#FR "France (la)"

parameters: #Parameters list - https://build.fhir.org/ig/FHIR/fhir-tools-ig/CodeSystem-ig-parameters.html
    shownav: 'true'
    path-expansion-params: '../../expansion-params.json' # for using French SNOMED CT Extension
    pin-canonicals: pin-all
    apply-contact: true
    logging:
      - tx #tx: Messages describing the use of the terminology server (for debugging)
      - html #html: Log when validating an html page (troubleshooting only - leave off)
      - generate #generate: Log when producing an individual resource (troubleshooting only - leave off)
      - init #init: Messages describing the start up process (for debugging)
      - progress #progress: Overall progress messages
    i18n-default-lang: fr # Default language
    apply-jurisdiction: true
    i18n-lang:
      - en
    translation-sources:
      - input/translations/en

dependencies:
  ans.fr.terminologies: latest
  ans.fhir.fr.document-core: current
  ans.cda.fr.document-core: current


pages:
    index.md:
        title: Accueil
    structureGenerale.md:
        title: Structure générale document
        introduction.md:
            title: Introduction
        exigencesSpecifiques.md:
            title: Exigences spécifiques
        mappingCDA-FHIR-struc-gen.md:
            title: Mapping CDA / FHIR
    enteteDocument.md:
        title: Entête document
        mappingCDA-FHIR-entete.md:
            title: Mapping Métier/CDA/FHIR
    corpsDocument.md:
        title: Corps d'un document
        mappingCDA-FHIR-corps.md:
            title: Mapping Métier/CDA/FHIR
    autres_ressources.md:
        title: Autres Ressources
        securite.md:
            title: Sécurité
        downloads.md:
            title: Téléchargements et usages
    translationinfo.md:
        title: Informations sur la traduction

menu:
    Accueil: index.html
    Structure générale document:
        Introduction: introduction.html
        Exigences spécifiques: exigencesSpecifiques.html
        Mapping CDA / FHIR: mappingCDA-FHIR-struc-gen.html
    Entête document:
        Modèle logique métier: StructureDefinition-fr-lm-header-document.html
        Mapping Métier/CDA/FHIR: mappingCDA-FHIR-entete.html
    Corps d'un document:
        Modèle logique métier: StructureDefinition-fr-lm-corps-document.html
        Mapping Métier/CDA/FHIR: mappingCDA-FHIR-corps.html
    Ressources de conformité: artifacts.html
    Autres ressources:
        "IG FHIR": new-tab https://interop.esante.gouv.fr/ig/fhir/document-core/index.html
        "IG CDA": new-tab https://interop.esante.gouv.fr/ig/cda/document-core/index.html
        "Espace de publication du CI-SIS": new-tab https://esante.gouv.fr/offres-services/ci-sis/espace-publication
        "Serveur Multi-terminologies": new-tab https://smt.esante.gouv.fr/
        "Serveur Multi-terminologies / FHIR": new-tab https://smt.esante.gouv.fr/fhir
        "IG terminologies et jeux de valeurs du CI-SIS": new-tab https://ansforge.github.io/IG-terminologie-de-sante/ig/main/index.html
        "Espace de tests du CI-SIS": new-tab https://interop.esante.gouv.fr/
        Sécurité: securite.html
        "Standard CDA": new-tab https://hl7.org/cda/stds/online-navigation/index.html
        "Standard FHIR": new-tab https://hl7.org/fhir/R4/index.html
        "Documentation des guides d'implémentation de l'ANS": new-tab https://interop.esante.gouv.fr/ig/documentation/index.html
        Téléchargements et usage: downloads.html

groups:
  metier-entete:
  # Les apostrophes semblent poser pb dans les name faisant apparaître des champs vides dans la page artifact
    name: Modèles logiques métier entête de document
    resources:
      - FRLMHeaderDocument	
      - FRLMPatient
      - FRLMHealthProfessional
      - FRLMOrganisation
      - FRLMInformant
      - FRLMIntendedRecipient
      - FRLMLegalAuthentication
      - FRLMAttester
      - FRLMDataEnterer
      - FRLMParticipant
      - FRLMOrder
      - FRLMConsent
      - FRLMLocation
      - FRLMRelatedPerson
      - FRLMHumanName

  metier-sections: 
    name: Modèles logiques métier sections de document
    resources:
      - StructureDefinition/FRLMCorpsDocument
      #Sections
      - StructureDefinition/FRLMSection
      - StructureDefinition/FRLMAllergiesAndIntolerances
      - StructureDefinition/FRLMFamilyMedicalHistory
      - StructureDefinition/FRLMHistoryOfPastIllness
      - StructureDefinition/FRLMQRCode
      - StructureDefinition/FRLMNote
      - StructureDefinition/FRLMAddendum
      - StructureDefinition/FRLMObservationResults
      - StructureDefinition/FRLMAdvanceDirectives
      - StructureDefinition/FRLMMedicalDevicesAndImplants
      - StructureDefinition/FRLMPresentedForm
      - StructureDefinition/FRLMAttachments
      - StructureDefinition/FRLMPredictableAdverseDrugReaction
      - StructureDefinition/FRLMHazardousWorkingConditions
      - StructureDefinition/FRLMSocialHistory
      - StructureDefinition/FRLMProcedures
      - StructureDefinition/FRLMResultData
      - StructureDefinition/FRLMExaminationReport
      - StructureDefinition/FRLMOrderInformation
      - StructureDefinition/FRLMComparisonStudy
      - StructureDefinition/FRLMExposureInformation
      - StructureDefinition/FRLMSupportingInformation
      - StructureDefinition/FRLMDicomStudyMetadata
      - StructureDefinition/FRLMRecommendation
      - StructureDefinition/FRLMConclusion
      - StructureDefinition/FRLMMedicationDispensations
      - StructureDefinition/FRLMPatientEducation
      - StructureDefinition/FRLMSectionPregnancyHistory
      - StructureDefinition/FRLMCarePlans
      - StructureDefinition/FRLMMedicalDevicePrescriptions
      - StructureDefinition/FRLMMedicationPrescription
      - StructureDefinition/FRLMProblems
      - StructureDefinition/FRLMVitalSigns
      - StructureDefinition/FRLMFunctionalStatus
      - StructureDefinition/FRLMMedicationSummary
      - StructureDefinition/FRLMImmunisations
      - StructureDefinition/FRLMReasonForReferral
      - StructureDefinition/FRLMCourseOfEncounter
      - StructureDefinition/FRLMHospitalDischargeMedications
      - StructureDefinition/FRLMAlerts
      - StructureDefinition/FRLMAdmissionEvaluation
      - StructureDefinition/FRLMEncounterInformation
      - StructureDefinition/FRLMPatientHistory
      - StructureDefinition/FRLMSectionTravelHistory
      - StructureDefinition/FRLMPatientStory

  metier-composants-communs: 
    name: Modèles logiques métier des composants communs
    description: Modèles de données métier représentant les concepts communs, modélisés indépendamment de la syntaxe et de façon plus accessible pour le métier que les éléments techniques CDA et FHIR.
    resources:
      - StructureDefinition/FRLMEntry
      - StructureDefinition/FRLMProcedure
      - StructureDefinition/FRLMFamilyMemberHistory
      - StructureDefinition/FRLMServiceRequest
      - StructureDefinition/FRLMCarePlan
      - StructureDefinition/FRLMCondition
      - StructureDefinition/FRLMEncounter
      - StructureDefinition/FRLMObservation
      - StructureDefinition/FRLMAllergyIntolerance	
      - StructureDefinition/FRLMAdvanceDirective
      - StructureDefinition/FRLMDeviceUse
      - StructureDefinition/FRLMAttachment
      - StructureDefinition/FRLMAdverseDrugReaction
      - StructureDefinition/FRLMObservationAssessment
      - StructureDefinition/FRLMObservationSocialHistory
      - StructureDefinition/FRLMObservationMedia
      - StructureDefinition/FRLMPregnancyObservation
      - StructureDefinition/FRLMPregnancyStatus
      - StructureDefinition/FRLMPregnancyHistory
      - StructureDefinition/FRLMMedication
      - StructureDefinition/FRLMDoseNumber
      - StructureDefinition/FRLMResultatsExamensBiologieMedicale
      - StructureDefinition/FRLMObservationVitalSign
      - StructureDefinition/FRLMMedicationAdministration
      - StructureDefinition/FRLMDICOMMedicationAdministration
      - StructureDefinition/FRLMImmunisation
      - StructureDefinition/FRLMMedicationDispense
      - StructureDefinition/FRLMSpecimen
      - StructureDefinition/FRLMBatterieExamensBiologieMedicale
      - StructureDefinition/FRLMIsolatMicrobiologique
      - StructureDefinition/FRLMResultatExamensBiologieElementCliniquePertinent
      - StructureDefinition/FRLMImagingStudy
      - StructureDefinition/FRLMSeries
      - StructureDefinition/FRLMSOPInstance
      - StructureDefinition/FRLMPrescriptionItem
      - StructureDefinition/FRLMQuantityExposure
      - StructureDefinition/FRLMTransfusionDeProduitsSanguins
      - StructureDefinition/FRLMMultidrugResistantMicroorganismIdentification
      - StructureDefinition/FRLMTransfusionAccidents
      - StructureDefinition/FRLMPatientTransfer
      - StructureDefinition/FRLMLaboratoireExecutant
      - StructureDefinition/FRLMDevice
      - StructureDefinition/FRLMDosageInstructions
      - StructureDefinition/FRLMPrescriptionEntree
      - StructureDefinition/FRLMLaboratoryObservation
      - StructureDefinition/FRLMBodyStructure
      - StructureDefinition/FRLMTravelHistory
      - StructureDefinition/FRLMAlert
      - StructureDefinition/FRLMEndpoint
      - StructureDefinition/FRLMMedicationUse
      - StructureDefinition/FRLMMicroOrganismSearch
      
  mapping-entete:
    name: Concept Maps entête de document
    resources:
      - FRHeaderDocumentLMCDAFHIR
      - FRPatientLMCDAFHIR
      - FRAuthorLMCDAFHIR
      - FRDataEntererLMCDAFHIR
      - FRInformantLMCDAFHIR
      - FRCustodianLMCDAFHIR
      - FRIntendedRecipientLMCDAFHIR
      - FRLegalAuthenticationLMCDAFHIR
      - FRAttesterLMCDAFHIR
      - FRParticipantHeaderLMCDAFHIR
      - FROrderLMCDAFHIR
      - FRConsentLMCDAFHIR
      - FRHealthProfessionalLMCDAFHIR
      - FROrganisationLMCDAFHIR
      - FRRelatedPersonLMCDAFHIR

  mapping-sections:
    name: Concept Maps sections de document
    resources:
      - FRSectionSupportingInformationLMCDAFHIR
      - FRSectionOrderInformationLMCDAFHIR
      - FRSectionExposureInformationLMCDAFHIR
      - FRSectionExaminationReportLMCDAFHIR
      - FRSectionAddendumLMCDAFHIR
      - FRSectionSocialHistoryLMCDAFHIR
      - FRSectionFunctionalStatusLMCDAFHIR
      - FRSectionAllergiesAndIntolerancesLMCDAFHIR
      - FRSectionFamilyMedicalHistoryLMCDAFHIR
      - FRSectionQRCodeLMCDAFHIR
      - FRSectionNoteLMCDAFHIR
      - FRSectionComparisonStudyLMCDAFHIR
      - FRSectionConclusionLMCDAFHIR
      - FRSectionMedicalHistoryLMCDAFHIR
      - FRSectionLaboratoryChapterLMCDAFHIR
      - FRSectionLaboratorySubChapterLMCDAFHIR
      - FRSectionAdvanceDirectivesLMCDAFHIR
      - FRSectionMedicalDevicesAndImplantsLMCDAFHIR
      - FRSectionPresentedFormLMCDAFHIR
      - FRSectionAttachmentsLMCDAFHIR
      - FRSectionPredictableAdverseDrugReactionLMCDAFHIR
      - FRSectionPatientEducationLMCDAFHIR
      - FRSectionHazardousWorkingConditionsLMCDAFHIR
      - FRSectionProceduresLMCDAFHIR
      - FRSectionPregnancyHistoryLMCDAFHIR
      - FRSectionDicomStudyMetadataLMCDAFHIR
      - FRSectionCarePlansLMCDAFHIR
      - FRSectionAlertsLMCDAFHIR
      - FRSectionMedicalDevicePrescriptionsLMCDAFHIR
      - FRSectionMedicationRequestLMCDAFHIR
      - FRSectionProblemsLMCDAFHIR
      - FRSectionReasonForReferralLMCDAFHIR
      - FRSectionResultsLMCDAFHIR
      - FRSectionLaboratorySecondIntentionResultsLMCDAFHIR
      - FRSectionVitalSignsLMCDAFHIR
      - FRSectionMedicationSummaryLMCDAFHIR
      - FRSectionHospitalDischargeMedicationsLMCDAFHIR
      - FRSectionImmunisationsLMCDAFHIR
      - FRSectionMedicationDispenseLMCDAFHIR

  mapping-composants-communs:
    name: Concept Maps des composants communs de Document
    resources:
      - FRProcedureLMCDAFHIR
      - FRAdvanceDirectiveLMCDAFHIR
      - FRAdverseDrugReactionLMCDAFHIR
      - FRAllergyIntoleranceLMCDAFHIR
      - FRCarePlanLMCDAFHIR
      - FRConditionLMCDAFHIR
      - FRDeviceLMCDAFHIR
      - FRDeviceUseLMCDAFHIR
      - FRAttachmentLMCDAFHIR
      - FREncounterLMCDAFHIR
      - FRFamilyMemberHistoryLMCDAFHIR
      - FRImagingStudyLMCDAFHIR
      - FRImagingProcedureLMCDAFHIR
      - FRImagingSeriesLMCDAFHIR
      - FRImmunisationLMCDAFHIR
      - FRMediaLMCDAFHIR
      - FRMedicationAdministrationLMCDAFHIR
      - FRMedicationDispenseLMCDAFHIR
      - FRMedicationLMCDAFHIR
      - FRMedicationRequestLMCDAFHIR
      - FRMedicationStatementLMCDAFHIR
      - FRLaboratoryIsolateResultsLMCDAFHIR
      - FRLaboratoryBatteryResultsLMCDAFHIR
      - FRLaboratoryResultsLMCDAFHIR
      - FRLaboratoryResultClinicalElementLMCDAFHIR
      - FRObservationMicroorganismDetectionLMCDAFHIR
      - FRObservationMultiresistantMicroorganismsIdentificationLMCDAFHIR
      - FRObservationPregnancyLMCDAFHIR
      - FRImagingQuantityExposureLMCDAFHIR
      - FRObservationResultLMCDAFHIR
      - FRObservationSocialHistoryLMCDAFHIR
      - FRObservationAssessmentLMCDAFHIR
      - FRObservationVitalSignsLMCDAFHIR
      - FRPregnancyHistoryLMCDAFHIR
      - FRServiceRequestLMCDAFHIR
      - FRSpecimenLMCDAFHIR
      - FRImagingMedicationAministrationLMCDAFHIR
      - FRParticipantCorpsLMCDAFHIR
      - FRObservationLMCDAFHIR
